extends RefCounted
## The French table.
##
## English is the key (see `loc.gd`), so a row is `"the English as it is printed": "le français"`.
## Rows are grouped by the file they come from, which is how this is maintained: a new sentence in
## the interface is a new row here, and a sentence with no row is simply English that has not been
## translated *yet* rather than a hole in the screen.
##
## Two things to keep in mind when adding rows:
##
##   * **Keep the placeholders, and only the placeholders.** `%s`, `%d` and `%.1f` may be moved
##     around a French sentence — that is why the template is translated before the values go in —
##     but `%%` is a literal per cent and must survive as `%%`.
##   * **Match the source character for character.** The `·` separators, the trailing full stop,
##     the capital letters: the lookup is exact, and a row that does not match is a row that does
##     nothing at all, quietly.

const TABLE: Dictionary = {
	# ------------------------------------------------------------------ the control strip
	"WASD move · Shift run · Space jump · click to strike · Q dash · C cultivate · B break through":
		"Déplacements ZQSD · Maj course · Espace saut · clic frapper · Q esquive · C cultiver · B percée",
	"   ·   click to look around": "   ·   cliquez pour regarder autour",
	"   ·   CAMP WARDS — nothing here will follow you in":
		"   ·   SCEAUX DU CAMP — rien ne vous suivra ici",
	"   ·   MEDITATING — press C to stand": "   ·   MÉDITATION — appuyez sur C pour vous lever",
	"   ·   DASH ready": "   ·   ESQUIVE prête",
	"   ·   dash cooling": "   ·   esquive en recharge",
	"Click (or F) to strike — posts raise ATTACK, raiders drop crystals.":
		"Cliquez (ou F) pour frapper — les poteaux montent l'ATTAQUE, les pillards lâchent des cristaux.",
	"Tap 1, 2 or 3 to drill BODY: it costs blood, not qi, and widens your HP cap.":
		"Touches 1, 2 ou 3 pour entraîner le CORPS : ça coûte du sang, pas du qi, et élargit votre plafond de PV.",
	# The interact prompt. One line for the whole world, and the reason it exists is that the
	# tower's door was a conversation nobody could find the handle for.
	"E — %s": "E — %s",
	"speak with %s": "parler à %s",
	"speak with %s — %s": "parler à %s — %s",
	"the tower's door": "la porte de la tour",
	"take the stair": "prendre l'escalier",
	"go up": "monter",
	"the floor is not clear yet": "l'étage n'est pas encore net",
	"Qi Pressure — unavailable": "Pression de Qi — indisponible",
	"Qi Pressure — needs %.0f QI held (you have %.0f)":
		"Pression de Qi — demande %.0f QI détenu (vous en avez %.0f)",

	# ------------------------------------------------------------------ settings and panels
	"SETTINGS": "RÉGLAGES",
	"TRAINING CAPS": "PLAFONDS D'ENTRAÎNEMENT",
	"INTERFACE SIZE": "TAILLE DE L'INTERFACE",
	"AURA": "AURA",
	"LANGUAGE": "LANGUE",
	"VOICES": "VOIX",
	"On": "Activées",
	"Off": "Coupées",
	"Sliders cap at what you have earned. Train to raise the cap.":
		"Les curseurs s'arrêtent à ce que vous avez gagné. Entraînez-vous pour lever le plafond.",
	"Smaller": "Plus petit",
	"Bigger": "Plus grand",
	"Reset progress": "Effacer la progression",
	"Press Reset again to erase all progression.":
		"Appuyez encore sur Effacer pour tout perdre.",
	"Progress recorded.": "Progression enregistrée.",
	"Time holds while the panel is open.": "Le temps s'arrête pendant que le panneau est ouvert.",
	"Esc to step away": "Échap pour s'éloigner",
	"Step away": "S'éloigner",
	"Show every stat (V)": "Voir toutes les statistiques (V)",
	"Fold the stat readout away (V)": "Replier le relevé de statistiques (V)",
	"Show the map": "Afficher la carte",
	"Fold the map away": "Replier la carte",
	"THE ELDER'S SHELF": "L'ÉTAGÈRE DE L'ANCIEN",
	"Hand it in": "Le remettre",
	"Nothing left to teach": "Plus rien à enseigner",
	"Nothing to hand in": "Rien à remettre",
	"Not finished yet": "Pas encore fini",
	"All tasks complete": "Toutes les tâches accomplies",
	"You have finished every task he knows how to set.":
		"Vous avez accompli tout ce qu'il sait demander.",
	"The elder has nothing left to set.": "L'ancien n'a plus rien à demander.",
	"Every stat has become everything it was going to become.":
		"Chaque statistique est devenue tout ce qu'elle devait devenir.",
	"Every threshold in this stat is behind you.":
		"Tous les paliers de cette statistique sont derrière vous.",
	"No technique yet. Every stat turns into something at a multiple of its":
		"Pas encore de technique. Chaque statistique se transforme à un multiple de son",
	"nothing yet": "rien encore",
	"locked until": "bloqué jusqu'à",
	"a reward": "une récompense",
	"all it can give": "tout ce qu'elle peut donner",
	"every technique held": "chaque technique détenue",
	"how full": "remplissage",
	"things this body can do": "ce que ce corps sait faire",
	"INSIGHT FULL — press B to break through": "INTUITION PLEINE — B pour percer",
	"sold out": "épuisé",
	"Sold out": "Épuisé",

	# ------------------------------------------------------------------ the statistics
	"ATTACK": "ATTAQUE",
	"DEFENSE": "DÉFENSE",
	"SPEED": "VITESSE",
	"BODY": "CORPS",
	"Weathering damage": "Encaisser les coups",
	"Striking the training posts": "Frapper les poteaux d'entraînement",
	"Running (hold Shift)": "Courir (Maj maintenu)",
	"Pushups, squats and standing stance": "Pompes, squats et posture debout",
	"Toughening up under damage": "Endurcir le corps sous les coups",
	"1 xp per point of damage dealt to a post": "1 xp par point de dégât infligé à un poteau",
	"1 xp per metre run (hold Shift)": "1 xp par mètre couru (Maj maintenu)",
	"1 xp per rep of physical training": "1 xp par répétition d'entraînement physique",
	"1 xp per jump, scaled by how high you jumped": "1 xp par saut, selon la hauteur",
	"0.5 xp per point of damage weathered": "0,5 xp par point de dégât encaissé",
	"2 xp per point of damage weathered": "2 xp par point de dégât encaissé",
	"1 xp per 0.5 QI spent meditating": "1 xp par 0,5 QI dépensé en méditation",
	"Thick Skin": "Peau Épaisse",
	"Iron Skin": "Peau de Fer",
	"Jade Skin": "Peau de Jade",
	"Iron Bones": "Os de Fer",
	"Second Wind": "Second Souffle",
	"Deep Well": "Puits Profond",
	"Dantian Bell": "Cloche du Dantian",
	"Blood Boil": "Sang Bouillant",
	"Sky Step": "Pas du Ciel",
	"Cloud Step": "Pas des Nuages",
	"Qi Bolt": "Trait de Qi",
	"Iron Stance": "Posture de Fer",
	"Refining it while meditating": "L'affiner en méditation",
	"Out of a fight, wounds close three times as fast.":
		"Hors combat, les blessures se referment trois fois plus vite.",
	"Blows land eight per cent softer on a body that has been through a few.":
		"Les coups portent huit pour cent plus doux sur un corps qui en a vu.",
	"Everything is eight per cent softer on a body that has been through everything.":
		"Tout porte huit pour cent plus doux sur un corps qui a tout traversé.",
	"A trained hide over a trained frame: another twelve per cent off every blow.":
		"Une peau entraînée sur une charpente entraînée : encore douze pour cent en moins.",
	"Some of every blow you take is given back to the one who threw it.":
		"Une part de chaque coup reçu revient à celui qui l'a porté.",
	"A shell of qi eats one blow every eighteen seconds, out of the dantian.":
		"Une coque de qi absorbe un coup toutes les dix-huit secondes, prise sur le dantian.",
	"Once every ninety seconds, a killing blow leaves you standing at a quarter.":
		"Toutes les quatre-vingt-dix secondes, un coup fatal vous laisse debout à un quart.",
	"Blows no longer move you.": "Les coups ne vous déplacent plus.",
	"Falls hurt half as much and the safe drop is two metres deeper.":
		"Les chutes font moitié moins mal et la chute sûre gagne deux mètres.",
	"You get up twice as fast and do not slide half as far.":
		"Vous vous relevez deux fois plus vite et glissez deux fois moins loin.",
	"Below a third of your health, your blows land a quarter harder.":
		"Sous un tiers de vie, vos coups portent un quart plus fort.",
	"One blow in five lands crushing, for double.": "Un coup sur cinq écrase, pour le double.",
	"A deep well behind a hard wall: the jade shell comes back twice as fast.":
		"Un puits profond derrière un mur dur : la coque de jade revient deux fois plus vite.",
	"Qi Pressure costs a third less to hold.": "La Pression de Qi coûte un tiers de moins à tenir.",
	"A landing from six metres staggers everything within three and a half.":
		"Une chute de six mètres fait vaciller tout ce qui est à trois mètres et demi.",
	"The first three quarters of a second of a sprint is a third faster.":
		"Les trois premiers quarts de seconde d'un sprint sont un tiers plus rapides.",
	"Steeper ground stays runnable, and you are an eighth quicker than training alone.":
		"Les pentes raides restent courantables, et vous êtes un huitième plus rapide.",
	"One more jump in the air than training alone would allow.":
		"Un saut de plus en l'air que l'entraînement seul ne permet.",
	"Hold jump in the air and walk on it. It is paid for the whole time.":
		"Maintenez saut en l'air et marchez dessus. Ça se paie en continu.",
	"R throws a ball of your own aura at what you are looking at, for a ":
		"R lance une bille de votre propre aura sur ce que vous visée, pour un ",
	"twentieth of the dantian.": "vingtième du dantian.",
	"A new cultivator awakens.": "Un nouveau cultivateur s'éveille.",
	"Vitality and qi fully restored.": "Vitalité et qi entièrement restaurés.",
	"Progression wiped. A new cultivator awakens.":
		"Progression effacée. Un nouveau cultivateur s'éveille.",
	"Save file is not valid JSON; starting fresh.":
		"Le fichier de sauvegarde n'est pas un JSON valide ; on repart à zéro.",
	"nothing worn": "rien de porté",

	# ------------------------------------------------------------------ training drills
	"Iron Stance.": "Posture de Fer.",
	"Horse stance. Slow and stubborn, and it thickens the skin you hide behind.":
		"Posture du cheval. Lente et têtue, elle épaissit la peau qui vous abrite.",
	"Pure constitution. Costs the most blood and trains the most body.":
		"Constitution pure. Coûte le plus de sang et entraîne le plus le corps.",
	"Cheaper per rep, and the legs earn a little of the jump with them.":
		"Moins cher par répétition, et les jambes y gagnent un peu du saut.",
	"Nothing left in the tank. The set ends.": "Plus rien dans le réservoir. La série s'arrête.",

	# ------------------------------------------------------------------ the map and its legend
	"Village / tower": "Village / tour",
	"Raider camp": "Camp de pillards",
	"Camp wards": "Sceaux du camp",
	"camp wards (safe)": "sceaux du camp (sûr)",
	"Site you found": "Site découvert",
	"The elder": "L'ancien",
	"a reward is waiting": "une récompense attend",
	"there is something here for you": "il y a quelque chose ici pour vous",
	"50 m": "50 m",

	# ------------------------------------------------------------------ the villages
	"the road's start": "le début de la route",
	"the forge": "la forge",
	"keeper of the village": "gardien du village",
	"trader": "marchand",
	"physician": "guérisseuse",
	"the board": "le tableau",
	"the tower's foot": "le pied de la tour",
	"Hollowmere — a well, four roofs, and a palisade somebody mended twice.":
		"Hollowmere — un puits, quatre toits, et une palissade que quelqu'un a réparée deux fois.",
	"Stonewatch — hammer, smoke, and a palisade of new-cut timber.":
		"Stonewatch — marteau, fumée, et une palissade de bois fraîchement coupé.",
	"Towerfall — the spire's shadow lies over the whole square, and nobody looks up.":
		"Towerfall — l'ombre de la flèche couvre toute la place, et personne ne lève les yeux.",
	"You came down the road, so you are somebody's news. Sit. Nothing here is in a hurry.":
		"Vous arrivez par la route, alors vous êtes une nouvelle pour quelqu'un. Asseyez-vous. Rien n'est pressé ici.",
	"Mind the sparks. Everything here is either being made or being repaired.":
		"Attention aux étincelles. Ici tout est en train d'être fait ou réparé.",
	"You have seen it. Everybody who arrives has seen it. The question is why you came anyway.":
		"Vous l'avez vu. Tous ceux qui arrivent l'ont vu. La question, c'est pourquoi vous êtes venu quand même.",
	"a stranger": "un inconnu",
	"known by sight": "reconnu de vue",
	"talked about": "dont on parle",
	"You are somebody's rumour now, you know.": "Vous êtes une rumeur, maintenant, vous savez.",
	"Somebody said your name in the square and nobody asked who.":
		"Quelqu'un a dit votre nom sur la place et personne n'a demandé qui.",
	"They say your name now, further down the road. They say it carefully.":
		"Ils disent votre nom maintenant, plus loin sur la route. Ils le disent prudemment.",
	"They have stopped asking what you want and started asking what you need.":
		"Ils ont cessé de demander ce que vous voulez et commencent à demander ce qu'il vous faut.",
	"They look at you the way people look at weather coming in.":
		"Ils vous regardent comme on regarde le temps qui arrive.",
	"Elder Mei": "Ancienne Mei",
	"Tao the Pedlar": "Tao le Colporteur",
	"Grandmother Nuo": "Grand-mère Nuo",
	"Watchman Gu": "Gu la Vigie",
	"Little Shen": "Petit Shen",
	"Forgemaster Du": "Maître Forgeron Du",
	"Physician Rao": "Médecin Rao",
	"Captain Zhu": "Capitaine Zhu",
	"Sergeant Ou": "Sergent Ou",
	"Sister Lan": "Sœur Lan",
	"Scholar Yun": "Érudit Yun",
	"Old Wen": "Vieil Wen",
	"Iron Auntie": "Tante de Fer",
	"Warden Bai": "Gardien Bai",
	"Apprentice Fen": "Apprenti Fen",
	"Forgemaster Du — the anvil": "Maître Forgeron Du — l'enclume",
	"Scholar Yun has been reading the same three pages for nine years.":
		"L'érudit Yun relit les mêmes trois pages depuis neuf ans.",
	"Worn now.": "Porté en ce moment.",
	"Yours, and not on.": "À vous, et pas porté.",
	"wear it": "le porter",
	"take it": "le prendre",
	"Not enough crystals for that one.": "Pas assez de cristaux pour celui-là.",
	"Not enough crystals for another.": "Pas assez de cristaux pour en reprendre un.",
	"Not enough of what it is made of, or not enough crystals.":
		"Pas assez de matière, ou pas assez de cristaux.",
	"One in the belt.": "Un dans la ceinture.",
	"Nothing on the board": "Rien au tableau",
	"Nothing to forge yet": "Rien à forger pour l'instant",
	"Nothing of yours to settle there.": "Rien à vous à régler là-bas.",
	"Nothing in the valley has ever reached the hundredth floor.":
		"Rien dans la vallée n'a jamais atteint le centième étage.",
	"That name cannot be taken from here.": "Ce nom ne peut pas être pris d'ici.",
	"The clerk will have new names by tomorrow.": "Le greffier aura de nouveaux noms demain.",
	"Buy something to wear first — the traders at the other villages keep the pieces.":
		"Achetez d'abord quelque chose à porter — les marchands des autres villages gardent les pièces.",
	"Stand still and let Elder Mei tell you what you have walked into.":
		"Restez immobile et laissez l'Ancienne Mei vous dire dans quoi vous venez d'entrer.",
	"Carry Mei's letter to Warden Bai in Stonewatch, past the ward.":
		"Portez la lettre de Mei au Gardien Bai à Stonewatch, au-delà du sceau.",
	"Du will work for four Hide Scrap. The near raiders carry them.":
		"Du travaillera pour quatre Morceaux de Peau. Les pillards proches en portent.",
	"Du has finished a commission for Towerfall. Carry it there.":
		"Du a fini une commande pour Towerfall. Portez-la là-bas.",
	"Come back from the tenth floor of the tower alive.":
		"Revenez vivant du dixième étage de la tour.",
	"The last champion is standing on the last spirit zone. Take it from it.":
		"Le dernier champion se tient sur la dernière zone spirituelle. Prenez-la-lui.",
	"There is a place up the road nobody tends and everybody knows. Find it.":
		"Il y a un endroit en haut de la route que personne n'entretient et que tout le monde connaît. Trouvez-le.",
	"Ten floors": "Dix étages",
	"The top of the stair": "Le haut de l'escalier",
	"The Standing Circle": "Le Cercle Debout",
	"The Ninth's ground": "Le terrain du Neuvième",
	"The blade goes south": "La lame part vers le sud",
	"What the valley is": "Ce qu'est la vallée",
	"Why the tower is here": "Pourquoi la tour est là",
	"Scales for the forge": "Écailles pour la forge",
	"Something worth wearing": "Quelque chose qui vaut la peine d'être porté",
	"A sealed letter": "Une lettre scellée",
	"Mei's sealed letter": "La lettre scellée de Mei",
	"A heavier purse": "Une bourse plus lourde",
	"Du's commission, wrapped in oilcloth": "La commande de Du, en toile huilée",
	"It is down. Collect.": "Il est tombé. Allez le chercher.",
	"a step finished": "une étape terminée",
	"is down, then bring the proof back here.": "est tombé, alors rapportez la preuve ici.",
	"The gate goes back up, and the first stall opens before the last post is in.":
		"La porte se relève, et le premier étal ouvre avant que le dernier poteau soit planté.",

	# ------------------------------------------------------------------ the people
	"Master Ren": "Maître Ren",
	"Xia the Firekeeper": "Xia la Gardienne du Feu",
	"Old Bo": "Vieux Bo",
	"The Tower": "La Tour",
	"The Tower's Door": "La Porte de la Tour",
	"You are new here. It is in the shoulders.":
		"Tu es nouveau ici. Ça se voit aux épaules.",
	"You have grown since last I looked. It shows in how you stand.":
		"Tu as grandi depuis la dernière fois. Ça se voit à ta façon de te tenir.",
	"Not today": "Pas aujourd'hui",
	"Another time": "Une autre fois",
	"Not yet": "Pas encore",
	"I will live": "Je survivrai",
	"Say it again": "Redis-le",
	"Hand it over": "Remets-le",
	"What did I do for you?": "Qu'est-ce que j'ai fait pour vous ?",
	"What names?": "Quels noms ?",
	"What have you got?": "Qu'est-ce que vous avez ?",
	"Show me your shelf": "Montrez-moi votre étal",
	"Then show me the pills": "Alors montrez-moi les pilules",
	"Put something on the anvil": "Mettre quelque chose sur l'enclume",
	"Tell me what it is": "Dis-moi ce que c'est",
	"He should have his book": "Il devrait récupérer son livre",
	"Then let it stay lost": "Alors laisse-le perdu",
	"The road is worth more than they are": "La route vaut plus qu'eux",
	"Let them keep their fire": "Laissez-leur leur feu",
	"Teach me the heavier hand": "Enseigne-moi la main plus lourde",
	"Teach me the deeper breath": "Enseigne-moi le souffle plus profond",
	"Take the stair from the ground floor": "Prendre l'escalier depuis le rez-de-chaussée",
	"Go down one floor": "Descendre d'un étage",
	"Stay on this landing": "Rester sur ce palier",
	"Leave the tower": "Quitter la tour",
	"A step finished is a step paid.": "Une étape finie est une étape payée.",
	"All of them, at once.": "Toutes, d'un coup.",
	"Bring the material and the crystals and it comes out better.":
		"Apportez la matière et les cristaux et ça sortira meilleur.",
	"ATTACK cap permanently +8. The breath is closed to you.":
		"Plafond d'ATTAQUE +8 pour toujours. Le souffle vous est fermé.",
	"QI cap permanently +60. The hand is closed to you.":
		"Plafond de QI +60 pour toujours. La main vous est fermée.",
	"Those raiders will never raise a hand to you again. DEFENSE cap +6.":
		"Ces pillards ne lèveront plus jamais la main sur vous. Plafond de DÉFENSE +6.",
	"The nearest raider camp is cleared for good. +45 crystals.":
		"Le camp de pillards le plus proche est nettoyé pour de bon. +45 cristaux.",
	"Burn their camp with them in it, or take the road past it and let them live?":
		"Brûler leur camp avec eux dedans, ou prendre la route et les laisser vivre ?",
	"Ninety-nine floors you have not seen, and the ones you have are empty.":
		"Quatre-vingt-dix-neuf étages que vous n'avez pas vus, et ceux que vous connaissez sont vides.",
	"Ever downward is free, and a cleared floor stays clear.":
		"Descendre est toujours libre, et un étage nettoyé reste nettoyé.",
	"The way up is open.": "Le chemin vers le haut est ouvert.",
	"You keep the depth you have taken. You lose nothing but the climb.":
		"Vous gardez la profondeur prise. Vous ne perdez que l'ascension.",
	"The door does not move. It is waiting for a body with more behind it than it has in front of it.":
		"La porte ne bouge pas. Elle attend un corps qui a plus derrière lui que devant.",
	"The door does not answer.": "La porte ne répond pas.",
	"There is nothing above this one that will let you in.":
		"Rien au-dessus ne vous laissera entrer.",
	"There is nothing below you but the ground.": "Il n'y a rien sous vous que le sol.",
	"Then there is nothing to ask.": "Alors il n'y a plus rien à demander.",
	"Not yet — there is more to do before that.": "Pas encore — il reste des choses à faire.",
	"You cannot cover the fee, and she does not work on credit.":
		"Vous ne pouvez pas payer, et elle ne travaille pas à crédit.",
	"You cannot cover the price, and nobody in the valley works on credit.":
		"Vous ne pouvez pas payer, et personne dans la vallée ne travaille à crédit.",
	"It is standing. Whatever you were about to pay for, it was not that.":
		"Elle est debout. Quoi que vous alliez payer, ce n'était pas ça.",
	"They will not start it without the price in hand.":
		"Ils ne commenceront pas sans le prix en main.",
	"He carries other people's accounts.": "Il porte les comptes des autres.",
	"He is the one who asks what your hands are for.":
		"C'est lui qui demande à quoi servent vos mains.",
	"She has watched every camp smoke from up here.":
		"D'ici, elle a vu fumer tous les camps.",
	"Nobody has anything for sale until it is standing again.":
		"Personne n'a rien à vendre tant qu'elle n'est pas relevée.",

	# ------------------------------------------------------------------ the tasks
	"Find your feet": "Trouver ses marques",
	"The long road": "La longue route",
	"Blood on the road": "Du sang sur la route",
	"What is over the hill": "Ce qu'il y a derrière la colline",
	"Deep water": "Eau profonde",
	"Sit still until it moves": "Rester immobile jusqu'à ce que ça bouge",
	"A realm is not rushed.": "Un royaume ne se presse pas.",
	"you can walk": "vous pouvez marcher",
	"you can dash": "vous pouvez esquiver",
	"and a new trick": "et une nouvelle technique",
	"Every raider carries a shard or two.": "Chaque pillard porte un ou deux éclats.",
	"Shift to run. The metres count only while you are actually moving.":
		"Maj pour courir. Les mètres comptent seulement quand vous bougez vraiment.",
	"Press C to sit. A spirit zone does the same work faster.":
		"Appuyez sur C pour vous asseoir. Une zone spirituelle fait le même travail plus vite.",
	"Follow a road out of camp. Anything the map wants you to find is tall and lit.":
		"Suivez une route hors du camp. Ce que la carte veut vous faire trouver est haut et éclairé.",
	"Raiders keep to their own ground. Strike them, then step back out of reach.":
		"Les pillards restent sur leur terrain. Frappez, puis reculez hors de portée.",
	"The roads are levelled for exactly this.": "Les routes sont nivelées exactement pour ça.",
	"Jump again in mid-air once this is yours — and mind the landing.":
		"Sautez à nouveau en plein air une fois ceci à vous — et attention à l'atterrissage.",
	"Run {target} m in total.": "Courez {target} m au total.",
	"Run {target} m with Shift held. The road out of camp is the long one.":
		"Courez {target} m avec Maj maintenu. La route hors du camp est longue.",
	"Cultivate for {target} seconds in total.": "Cultivez pendant {target} secondes au total.",
	"Leave the ground {target} times.": "Quittez le sol {target} fois.",
	"Defeat {target} raiders at their camps.": "Battez {target} pillards dans leurs camps.",
	"Gather {target} crystals from the camps.": "Récoltez {target} cristaux dans les camps.",
	"Find {target} of the old places along the roads. They burn a light until you do.":
		"Trouvez {target} des vieux lieux le long des routes. Ils brûlent une lumière jusqu'à ce que vous le fassiez.",

	# ------------------------------------------------------------------ the valley's own lines
	"%s IS MARKED TONIGHT — be at the gate by %02d:00":
		"%s EST MARQUÉ CETTE NUIT — soyez à la porte avant %02dh00",
	"RAID ON %s — %d still standing": "RAID SUR %s — %d encore debout",
	"%s IS OPEN — %d crystals mends the gate":
		"%s EST OUVERT — %d cristaux pour relever la porte",
	"FLOOR %d of %d — %s": "ÉTAGE %d sur %d — %s",
	"%s — the watch holds this ground": "%s — la garde tient ce terrain",
	"WATCHED IN %s — %d crystals settles it": "SURVEILLÉ À %s — %d cristaux règlent ça",
	"%s IN %s — %d crystals, or the bars": "%s À %s — %d cristaux, ou les barreaux",
	"%d wound%s — the breath comes short": "%d blessure%s — le souffle est court",
	"the tower stands at %d": "la tour se tient au %d",
	"%s  ×%.1f qi": "%s  ×%.1f qi",
	"%s · Stage %d": "%s · Palier %d",
	"%s · %s": "%s · %s",
	"Stage %d · %s · %d crystals · power %s": "Palier %d · %s · %d cristaux · puissance %s",
	"Stat gain ×%.2f": "Gain de stat ×%.2f",
	"REFINEMENT %d   ·   next in %.0fs": "RAFFINEMENT %d   ·   prochain dans %.0fs",
	"%d wounds%s — the breath comes short": "%d blessures%s — le souffle est court",
	"%s — dormant, needs stage %d": "%s — dormante, palier %d requis",
	"Crystals %d": "Cristaux %d",

	# ------------------------------------------------------------------ the tower's bands
	"The Lower Stair": "L'Escalier Bas",
	"The Ash Landing": "Le Palier des Cendres",
	"The Iron Galleries": "Les Galeries de Fer",
	"The Choking Dark": "Le Noir Étouffant",
	"The Long Ascent": "La Longue Montée",
	"The Broken Sky": "Le Ciel Brisé",
	"The Twelve Halls": "Les Douze Salles",
	"The Quiet Floors": "Les Étages Silencieux",
	"The Ninth Landing": "Le Neuvième Palier",
	"The Seat": "Le Siège",

	# ------------------------------------------------------------------ the realms
	"Body Tempering": "Trempe du Corps",
	"Qi Condensation": "Condensation du Qi",
	"Foundation Establishment": "Établissement des Fondations",
	"Core Formation": "Formation du Noyau",
	"Nascent Soul": "Âme Naissante",
	"Soul Transformation": "Transformation de l'Âme",
	"Void Refinement": "Raffinement du Vide",
	"Body Integration": "Intégration du Corps",
	"Great Ascension": "Grande Ascension",
	"Immortal Ascension": "Ascension Immortelle",
	# ------------------------------------------------- translated from the game's own
	# strings, by `tools/translate_fr.py`. Same rules as everything above: the English
	# is the key, and the placeholders are checked before a row is written.

	"a gain": "un gain",
	"Iron-Hand of Bandit Hollow": "Poing de Fer de Creux-des-Bandits",
	"The Butcher": "Le Boucher",
	"Widowmaker": "Tueur-de-Veuves",
	"The Quiet Brother": "Le Frère Silencieux",
	"Red Lian": "Lian la Rouge",
	"Hollow Chen": "Chen du Creux",
	"The Leash": "La Laisse",
	"Ox": "Bœuf",
	"%s of %s": "%s de %s",
	"%s is at %s, in the ring past the %s ward. %d crystals when it is down.": "%s est à %s, dans l'anneau après le quartier %s. %d cristaux quand il est à terre.",
	"%s is down. The board in %s owes you %d crystals.": "%s est à terre. Le tableau à %s vous doit %d cristaux.",
	"+%d crystals": "+%d cristaux",
	"a mark brought in": "une marque rapportée",
	"+%d standing": "+%d de réputation",
	"%s settled: %s": "%s réglé : %s",
	"cultivate until dawn": "cultiver jusqu'à l'aube",
	"sleep until dawn": "dormir jusqu'à l'aube",
	"Dawn. The qi comes up with the light.": "Aube. Le qi monte avec la lumière.",
	"Dusk. The gates are closing in the villages.": "Crépuscule. Les portes se ferment dans les villages.",
	"Night. The zones run richer and the raiders see further.": "Nuit. Les zones rapportent plus et les pillards voient plus loin.",
	"Morning. The roads are busy again.": "Matin. Les routes sont de nouveau fréquentées.",
	"None": "Aucun",
	"No aura. Only your own skin between you and the world.": "Pas d'aura. Juste votre peau entre vous et le monde.",
	"Raw refined qi drawn off the dantian. Soft, steady, always awake.": "Qi brut raffiné tiré du dantian. Doux, régulier, toujours éveillé.",
	"Wind": "Vent",
	"A wide, fast spiral. Thin as breath and impossible to grasp.": "Une large spirale rapide. Fin comme un souffle et impossible à saisir.",
	"Water": "Eau",
	"Heavy droplets that rise and fall in a tide of their own.": "Gouttes lourdes qui montent et descendent dans une marée propre.",
	"Electric": "Électricité",
	"Arcs that snap around the body. Hard to hold, harder to watch.": "Arcs qui claquent autour du corps. Difficile à tenir, plus dur à regarder.",
	"Fire": "Feu",
	"A pillar fed by your own qi. Bright, hungry, and impossible to hide.": "Un pilier nourri par votre propre qi. Brillant, affamé et impossible à cacher.",
	"more qi per second": "plus de qi par seconde",
	"Your dantian is empty. Qi will recover on its own.": "Votre dantian est vide. Le qi se rétablira de lui-même.",
	"Refinement %d reached — stat gain now ×%.2f.": "Raffinement %d atteint — gain de stats maintenant ×%.2f.",
	"Insight %d%%": "Perspicacité %d%%",
	"Refine %d more": "Raffiner %d de plus",
	"The tower's stair answers nothing. Whatever you carried up is what you have.": "L'escalier de la tour ne répond à rien. Ce que vous avez emporté est ce que vous avez.",
	"Breakthrough not ready — %s.": "Percée pas prête — %s.",
	"New aura unlocked: %s.": "Nouvelle aura débloquée : %s.",
	"REALM ADVANCE — %s. All caps +%d%%, gain ×%.2f.": "AVANCÉE DE REGNE — %s. Tout majuscule +%d%%, gain ×%.2f.",
	"Breakthrough! %s. All caps +%d%%, gain ×%.2f.": "Percée ! %s. Tout majuscule +%d%%, gain ×%.2f.",
	"+20 ATTACK": "+20 ATTAQUE",
	"upgrade the coat": "améliorer le manteau",
	"Hide Scrap": "Chute de peau",
	"the raiders of the near rings": "les pillards des anneaux proches",
	"Iron Scale": "Écaille de Fer",
	"the raiders past the second ward": "les pillards au-delà de la seconde enceinte",
	"Ash Cinder": "Cendre Ardente",
	"the Ash Champion's ground": "le terrain du Champion Ardent",
	"Iron Heart": "Cœur de Fer",
	"the Iron Champion's ground": "le terrain du Champion de Fer",
	"Ninth Ember": "Braise Neuvième",
	"the Ninth's ground": "le terrain du Neuvième",
	"Tower Splinter": "Éclat de Tour",
	"the floors of the tower": "les étages de la tour",
	"Vein Jade": "Jade de Veine",
	"the Earth Vein's ground": "le terrain de la Veine Terrestre",
	"Spirit Dust": "Poussière d'Esprit",
	"raiders, marks and caravans": "pillards, marques et caravanes",
	"Jade Wraps": "Bandes de Jade",
	"Strips of hide wound tight. Every blow is yours, only more so.": "Bandes de cuir serrées. Chaque coup est le vôtre, en plus fort.",
	"Ash Blade": "Lame Ardente",
	"Quenched in the Ash Champion's own cinder.": "Trempée dans la cendre du Champion Ardent.",
	"Wind Edge": "Tranchant du Vent",
	"Ground out of a splinter of the tower's own stair.": "Taillé dans un éclat de l'escalier de la tour.",
	"Traveller's Hide": "Cuir du Voyageur",
	"Cured hide. It stops the road, not a champion.": "Cuir traité. Il arrête la route, pas un champion.",
	"Iron Shell Coat": "Manteau Carapace de Fer",
	"Scale over leather. The smith's answer to a fist.": "Écailles sur cuir. La réponse du forgeron à un poing.",
	"Storm Silk Robe": "Robe de Soie d'Orage",
	"Silk the colour of the sky over the outer reach.": "Soie de la couleur du ciel sur la lisière.",
	"Springwater Charm": "Talisman d'Eau Vive",
	"A stone from the Spirit Spring, on a cord.": "Une pierre de la Source des Esprits, sur un cordon.",
	"Vein Talisman": "Talisman de Veine",
	"Jade cut from the Earth Vein. It breathes with you.": "Jade tiré de la Veine Terrestre. Il respire avec vous.",
	"Peak Seal": "Sceau du Pic",
	"A seal from the Storm Peak, worn as a claim.": "Un sceau du Pic des Tempêtes, porté comme une revendication.",
	"Traveller's Lamp": "Lampe du Voyageur",
	"A hooded lamp on a belt hook. It lights the road, not the fight.": "Une lampe à capuchon sur un crochet de ceinture. Elle éclaire la route, pas le combat.",
	"Mending Pill": "Pilule de Réparation",
	"Closes one wound, or pours back a third of your health.": "Ferme une blessure, ou rend un tiers de votre santé.",
	"Qi Pill": "Pilule de Qi",
	"Blood Elixir": "Elixir de Sang",
	"Spirit Ward": "Garde Spirituelle",
	"Six tenths of every blow turned aside for 30 seconds.": "Six dixièmes de chaque coup déviés pendant 30 secondes.",
	"not owned": "pas possédé",
	"%s — %s %s.  -%d crystals.": "%s — %s %s. -%d cristaux.",
	"Blood Elixir — every blow lands heavier for %.0fs.": "Elixir de Sang — chaque coup porte plus lourd pendant %.0fs.",
	"Spirit Ward — the blows come in at six tenths for %.0fs.": "Garde Spirituelle — les coups arrivent à six dixièmes pendant %.0fs.",
	"is it the camp": "est-ce le camp",
	"someone saw you": "on vous a vu",
	"wait it out": "attendre",
	"a day passed": "un jour est passé",
	"A day has gone by. The villages have short memories: %s.": "Un jour est passé. Les villages ont la mémoire courte : %s.",
	"%s — %s. %s counts you %s.": "%s — %s. %s vous compte %s.",
	"The square goes quiet": "La place se vide",
	"The watch is coming. Bars, or the road.": "La garde arrive. Barreaux, ou la route.",
	"The fine is paid. %s will deal with you again.": "L'amende est payée. %s s'occupera de vous à nouveau.",
	"You are put behind the door of %s's watch house. Pay the fine at the bars, or force ": "On vous met derrière la porte de la guérite de %s. Payez l'amende aux barreaux, ou forcez ",
	"them — which they will remember.": "les — ce dont ils se souviendront.",
	"The bar gives. You are out — and they will remember.": "La barre cède. Vous êtes dehors — et ils s'en souviendront.",
	"A broken bar": "Une barre brisée",
	"A watchman walks you to the edge of the village and lets go of your collar.": "Un garde vous raccompagne à la sortie du village et lâche votre col.",
	"HP": "PV",
	"JUMP": "SAUTER",
	"Jumping": "Saut",
	"about to close": "sur le point de fermer",
	"four times your starting strength": "quatre fois votre force de départ",
	"Cleave": "Trancher",
	"Crushing": "Écraser",
	"Mending": "Réparer",
	"Unshaken": "Imperturbable",
	# ------------------------------------------------- translated from the game's own
	# strings, by `tools/translate_fr.py`. Same rules as everything above: the English
	# is the key, and the placeholders are checked before a row is written.

	"Warded": "Protégé",
	"Surefoot": "Pied sûr",
	"Burst": "Explosion",
	"Softfoot": "Pied léger",
	"Meteor": "Météore",
	"is this key real": "cette clé est-elle réelle",
	"invisible stat bonus": "bonus de statistique invisible",
	"how many jumps do I have": "combien de sauts vous reste-t-il",
	"how far along are you": "où en êtes-vous",
	"The jade shell takes it. Back in %.0fs.": "La carapace de jade absorbe. De retour dans %.0fs.",
	"SECOND WIND — you are still standing, at a quarter. Once every %.0fs.": "COUP DE GRÂCE — vous tenez encore, à un quart. Une fois toutes les %.0fs.",
	"Took %s damage.": "Subi %s dégâts.",
	"burn Bandit Hollow": "brûler le Creux des Bandits",
	"WOUNDED ×%d — blows land %d%% harder, the body mends %d%% slower. A healer, a pill, ": "BLESSÉ ×%d — les coups portent %d%% plus fort, le corps guérit %d%% plus lentement. Un guérisseur, une pilule, ",
	"or a spell at a spirit zone closes it.": "ou un sort dans une zone d'esprit la referme.",
	"A wound closes.%s": "Une blessure se referme.%s",
	" %d still open.": " %d encore ouvertes.",
	"Could not write save file: %s": "Impossible d'écrire le fichier de sauvegarde : %s",
	"Lightness": "Légèreté",
	"%s — done. Return to the elder.": "%s — fait. Retournez voir l'ancien.",
	"%s complete — %d crystals%s": "%s terminé — %d cristaux%s",
	" and a new trick": " et un nouveau tour",
	"Runners on the road at dusk. %s is marked tonight — %d raiders, at the gate by %02d:00.": "Des coureurs sur la route au crépuscule. %s est marqué ce soir — %d pillards, à la porte pour %02d:00.",
	"Raider": "Pillard",
	"the squad is broken": "l'escouade est brisée",
	"%d raiders are at %s's gate, and the watch is standing in front of it.": "%d pillards sont à la porte de %s, et la garde se tient devant.",
	"The watch sees you put one down, and remembers what you are.": "La garde vous voit en abattre un, et se souvient de ce que vous êtes.",
	"stood with the watch": "s'est tenu avec la garde",
	"%s's watch sees it. They will remember your face for the right reason.": "La garde de %s voit ça. Ils se souviendront de votre visage pour la bonne raison.",
	"the gate held the night": "la porte a tenu la nuit",
	"%s held. The watch walks its beat in the morning.": "%s a tenu. La garde fait sa ronde au matin.",
	"%s's gate is down, and the stalls with it.": "La porte de %s est à terre, et les étals avec.",
	"the gate went down": "la porte est tombée",
	"%s is open. They went through the fence and out the far side — the market is burned, and ": "%s est ouverte. Ils ont franchi la clôture et sont sortis de l'autre côté — le marché est brûlé, et ",
	"it stays shut until somebody mends the gate. %d crystals.": "elle reste fermée jusqu'à ce que quelqu'un répare la porte. %d cristaux.",
	"paid for the gate": "payé pour la porte",
	"The gate at %s goes back up. Somebody says so, and nobody looks at you for long.": "La porte à %s est de nouveau levée. Quelqu'un le dit, et personne ne vous regarde longtemps.",
	"Toughened hide": "Peau endurcie",
	"+8 HP held": "+8 PV tenus",
	"Deeper dantian": "Dantian profond",
	"+5 QI held": "+5 Qi contenu",
	"Heavier hands": "Mains plus lourdes",
	"+0.8 ATTACK": "+0.8 ATTAQUE",
	"Calloused skin": "Peau calleuse",
	"+0.8 DEFENSE": "+0.8 DÉFENSE",
	"Harder legs": "Jambes plus dures",
	"+0.4 m/s SPEED cap": "+0.4 m/s VITESSE max",
	"Spring soles": "Semelles à ressort",
	"+0.20 m JUMP cap": "+0.20 m SAUT max",
	"Sharper step": "Pas plus vif",
	"-0.2 s dash cooldown": "-0.2 s temps de recharge de l'élan",
	"Air step": "Pas aérien",
	"+1 jump in mid-air": "+1 saut en l'air",
	"%s — %s cap +%s.  -%d crystals.": "%s — %s max +%s.  -%d cristaux.",
	"%s — %s.  -%d crystals.": "%s — %s.  -%d cristaux.",
	"the hand": "la main",
	"Stand there a moment. Feet apart. Yes — you have been running, not standing.": "Restez là un instant. Pieds écartés. Oui — vous avez couru, pas posé.",
	"the fire": "le feu",
	"The fire is for whoever comes back. It does not ask what you did out there.": "Le feu est pour celui qui revient. Il ne demande pas ce que vous avez fait dehors.",
	"the road": "la route",
	"Mm. Walk with me a little. I have the legs for it and nothing else.": "Mm. Marchez un peu avec moi. J'ai les jambes pour ça et rien d'autre.",
	"a thing the road warns about": "une chose dont la route avertit",
	"I have heard what you did. I would rather not be the one who repeats it.": "J'ai entendu ce que vous avez fait. Je préférerais ne pas être celui qui le répète.",
	"You can be taught one thing today, and only one, because the two of them are ": "Vous ne pouvez apprendre qu'une chose aujourd'hui, et une seule, car les deux sont ",
	"opposite answers. A heavier hand, or a deeper breath. Which is it?": "des réponses opposées. Une main plus lourde, ou une respiration plus profonde. Laquelle est-ce ?",
	"\"Then that is what you are. Come back when you have used it.\"": "\"Alors c'est ce que vous êtes. Revenez quand vous l'aurez utilisé.\"",
	"You have been out there, so you know. The raiders burn the road for whoever ": "Vous avez été dehors, vous savez donc. Les pillards brûlent la route pour quiconque ",
	"walks it — and they were somebody's sons before they were anybody's problem. ": "la parcourt — et ils étaient les fils de quelqu'un avant d'être le problème de qui que ce soit. ",
	"\"I will remember you said it, whatever comes of it.\"": "\"Je me souviendrai que vous l'avez dit, quoi qu'il en advienne.\"",
	"Found this on the road. The elder's own ledger, with his prices in it. I could ": "J'ai trouvé ceci sur la route. Le registre de l'ancien lui-même, avec ses prix. Je pourrais ",
	"walk it back to him, or we could both just... not notice.": "le lui rapporter, ou nous pourrions simplement... ne pas le remarquer.",
	"The elder's shelf gets 12% cheaper, permanently.": "L'étagère de l'ancien coûte 12% moins cher, définitivement.",
	"+60 crystals in his pocket and yours, once.": "+60 cristaux dans sa poche et la vôtre, une fois.",
	"\"Road's long. I will be seeing you on it.\"": "\"La route est longue. Je vous verrai dessus.\"",
	"something is asking me a question": "quelque chose me pose une question",
	"Somebody": "Quelqu'un",
	"%s: \"%s\"": "%s : « %s »",
	"You already chose. %s": "Vous avez déjà choisi. %s",
	"what did you buy at\n Hollowmere": "ce que vous avez acheté à\n Hollowmere",
	"%s: %s": "%s : %s",
	"Mend the gate — %d crystals": "Réparez le portail — %d cristaux",
	"You are %d crystals short of it.": "Il vous manque %d cristaux.",
	"%s is a gap in a fence, and it can be seen from the road.": "%s est une brèche dans une clôture, et elle est visible depuis la route.",
	" Nobody has anything for sale until it is standing again.": " Personne n'a rien à vendre tant qu'il ne tient pas debout à nouveau.",
	"\"%s\" %s will not serve you, and does not pretend otherwise.": "« %s » %s ne vous servira pas, et ne prétend pas le contraire.",
	"\"%s\" %s\"%s\"": "« %s » %s « %s »",
	"Wares, pieces and pills — %s's own share of the valley's.": "Marchandises, pièces et pilules — la part de %s de la vallée.",
	"\"%s\" You are carrying %d wound%s. They do not close on their own, and the ": "\"%s\" Vous portez %d blessure%s. Elles ne se referment pas d'elles-mêmes, et la ",
	"road out there is not getting shorter.": "route là-bas ne raccourcit pas.",
	"Close them — %d crystals": "Refermez-les — %d cristaux",
	"\"%s\" Nothing wrong with you that a walk would not fix. Pills, though, are ": "\"%s\" Rien qui ne se guérisse par la marche. Les pilules, cependant, sont ",
	"cheap today.": "bon marché aujourd'hui.",
	"\"%s\" %s has a board, and the board has names on it.": "\"%s\" %s a un tableau, et le tableau a des noms dessus.",
	"\"%s\" %s The village has one thing it cannot do for itself, and you are ": "\"%s\" %s a une chose qu'il ne peut faire pour lui-même, et vous êtes ",
	"walking out of that gate either way.": "en train de sortir par cette porte de toute façon.",
	"This is the village's whole story, and it is three steps long.": "C'est toute l'histoire du village, et elle tient en trois pas.",
	"\"%s\" %s has nothing left to ask of you. That is not the same as nothing ": "\"%s\" %s n'a plus rien à vous demander. Ce n'est pas la même chose que rien ",
	"left to say, but it is what I can do.": "à dire, mais c'est ce que je peux faire.",
	"\"%s\" Then it is done. %s": "\"%s\" Alors c'est fait. %s",
	"what did you decide about the raiders": "qu'avez-vous décidé au sujet des pillards",
	"It is done: %s. %s": "C'est fait : %s. %s",
	" Next: %s": " Suivant : %s",
	"It costs %d crystals and hurts, and then you are whole again.": "Ça coûte %d cristaux et ça fait mal, et ensuite vous êtes de nouveau entier.",
	"Step off at floor %d": "Descendez à l'étage %d",
	"The deepest anybody has taken this stair: %d of %d.": "Le plus profond que quiconque ait jamais pris cet escalier : %d sur %d.",
	"Stone, four hundred metres of it, and a doorway with no gate in it. ": "De la pierre, quatre cents mètres, et une porte sans battant. ",
	"It has been open the whole time. Deepest so far: %d of %d.": "Elle a été ouverte tout ce temps. Le plus profond jusqu'ici : %d sur %d.",
	"Go up to floor %d": "Montez à l'étage %d",
	"Floor %d": "Étage %d",
	"how far can I get": "jusqu'où pouvez-vous aller",
	"The Keeper of the Landing": "Le Gardien de l'Étage",
	"It has swept this landing for a hundred years and it will not be told to stop.": "Il a balayé cet étage pendant cent ans et on ne lui a pas dit de s'arrêter.",
	"The Ash Warden": "Le Gardien des Cendres",
	"It wears what the first ward left of its own champion.": "Il porte ce que le premier rempart a laissé de son propre champion.",
	"The Iron Steward": "L'Intendant de Fer",
	"Iron on every wall, and it has been counting the pieces.": "Du fer sur chaque mur, et il a compté les pièces.",
	"The Blind Cantor": "Le Chantre Aveugle",
	"It has not needed eyes for a long time.": "Il n'a pas eu besoin d'yeux depuis longtemps.",
	"The Tireless": "L'Infatigable",
	"You have climbed further than it expected. It intends to fix that.": "Vous avez grimpé plus loin qu'il ne s'y attendait. Il a l'intention d'y remédier.",
	"The Sky-Eater": "Le Dévoreur de Ciel",
	"The windows up here look out on nothing at all.": "Les fenêtres ici donnent sur le vide.",
	"The Twelfth Warden": "Le Douzième Gardien",
	"There were twelve of you once, it says. There is one of you now.": "Il y avait douze d'entre vous autrefois, dit-il. Il n'y en a plus qu'un.",
	"The Quiet One": "Le Silencieux",
	"The floors it keeps are silent. It would like to keep yours.": "Les étages qu'il garde sont silencieux. Il aimerait garder le vôtre.",
	"The Ninth's Shadow": "L'Ombre du Neuvième",
	"The Ninth left something behind on the way down. It has been waiting.": "Le Neuvième a laissé quelque chose en descendant. Il attend.",
	"The Unnamed": "L'Innommé",
	"The wards were built around this floor, and this floor has been awake the whole time.": "Les remparts ont été construits autour de cet étage, et cet étage est éveillé depuis le début.",
	"The door answers %s, or two wards crossed. You are %s.": "La porte répond à %s, ou à deux remparts croisés. Vous êtes %s.",
	"a higher realm": "un royaume supérieur",
	"The stair turns, and the air changes.": "L'escalier tourne, et l'air change.",
	"Somebody scratched a count into the wall here. The last number is not finished.": "Quelqu'un a gravé un compte sur le mur. Le dernier chiffre n'est pas terminé.",
	"A landing with no window, and a draught coming from somewhere.": "Une palier sans fenêtre, et un courant d'air venant d'ailleurs.",
	"Old blood on the floor, and a broom left standing in it.": "Du vieux sang sur le sol, et un balai planté dedans.",
	"The steps are worn deepest in the middle, from feet that were not hurrying.": "Les marches sont les plus usées au milieu, par des pieds qui ne se pressaient pas.",
	"A door in the wall that opens onto more wall.": "Une porte dans le mur qui donne sur plus de mur.",
	"Something has been stacked here, neatly, for a long time.": "Quelque chose a été empilé ici, proprement, pendant longtemps.",
	"The light comes from the stone itself on this floor.": "La lumière vient de la pierre elle-même à cet étage.",
	"Names, cut into the wall in a hand that gets worse as it goes down.": "Des noms, gravés dans le mur d'une main qui empire en descendant.",
	"Quiet, in the way a room is quiet after an argument.": "Calme, de la façon dont une pièce est calme après une dispute.",
	"The door lets you in at floor %d — %s.": "La porte vous fait entrer à l'étage %d — %s.",
	"walked out": "est sorti",
	"Floor %d. %s — the deepest anybody has taken this stair.": "Étage %d. %s — le plus profond que quiconque ait jamais monté cet escalier.",
	"Floor %d of %d cleared.%s": "Étage %d sur %d nettoyé.%s",
	"The tower puts you out. Floor %d stands at %d.%s": "La tour vous expulse. L'étage %d est à %d.%s",
	" Nothing in the valley has been further.": "Rien dans la vallée n'est allé plus loin.",
	"carried out": "a été sorti",
	"deepest %d/%d, %d runs, %d cleared, %d deaths inside": "plus profond %d/%d, %d courses, %d nettoyés, %d morts à l'intérieur",
	"how much qi is enough": "quelle quantité de qi est suffisante",
	"Pushups": "Pompes",
	"Qi Cripple": "Écrasement du Qi",
	"Idle": "Inactif",
	"Breath driven through the meridians until they give. ": "Le souffle parcourant les méridiens jusqu'à ce qu'ils cèdent. ",
	"Costs blood and qi, and the deeper the dantian the faster it goes.": "Coûte sang et qi, et plus le dantian est profond, plus ça va vite.",
	"it costs more qi": "ça coûte plus de qi",
	"the set you are in": "la série où vous êtes",
	"The breath runs out. The set ends.": "Le souffle s'épuise. La série s'achève.",
	"%d %s. Body remembers.": "%d %s. Le corps se souvient.",
	"the deeper you are, the faster the work goes": "plus vous êtes profond, plus le travail va vite",
	"Stonewatch": "Garde de pierre",
	"Have anything forged to *good* — one upgrade at the anvil.": "Faites forger n'importe quoi à *bon* — une amélioration à l'enclume.",
	"which village does this belong to": "à quel village cela appartient",
	"%s counts you %s now.": "%s vous compte %s maintenant.",
	"take this there": "prenez ceci là",
	"carrying: %s": "en cours : %s",
	"You are carrying %s.": "Vous portez %s.",
	"%s handed over.": "%s remis.",
	"%s has work for you.": "%s a du travail pour vous.",
	"%s is on.": "%s est en cours.",
	"%s is yours, and it is on you.": "%s est à vous, et c'est sur vous.",
	"%s comes off the anvil better than it went on.": "%s sort de l'enclume mieux qu'elle n'y est entrée.",
	"Settled: %s": "Réglé : %s",
	"%d crystals": "%d cristaux",
	" The anvil at Stonewatch can take it further.": "L'enclume de la Garde de pierre peut aller plus loin.",
	" Nothing better exists.": "Rien de mieux n'existe.",
	"The shutters are up. %s will not sell to an outlaw.": "Les volets sont levés. %s ne vendra pas à un hors-la-loi.",
	"  Everything is %d%% dearer until they forget.": "  Tout est %d%% plus cher jusqu'à ce qu'ils oublient.",
	"%s — what is for sale": "%s — ce qui est à vendre",
	"PIECES": "PIÈCES",
	"Nothing better exists.": "Rien de mieux n'existe.",
	"%s and %d crystals.": "%s et %d cristaux.",
	"Material and crystals, and it comes out better than it went on. It will never ": "Matière et cristaux, et ça sort mieux qu'en entrant. Ça ne va jamais ",
	"be worth more than the arm swinging it.": "valoir plus que le bras qui le manie.",
	"%s — settled": "%s — réglé",
	"%s%s  %d crystals on the body.": "%s%s  %d cristaux sur le corps.",
	", taken — it is waiting for you.": ", pris — il vous attend.",
	"%s — the board": "%s — le tableau",
	"A name is a contract. Take one and the body stands at that camp until it ": "Un nom est un contrat. Prenez-en un et le corps reste à ce camp jusqu'à ce qu'il ",
	"Carrying: %s": "Porté : %s",
	"Somebody in another village is waiting for it.": "Quelqu'un dans un autre village l'attend.",
	"Done: %s": "Fait : %s",
	"%s — the record": "%s — le registre",
	"the longest one that appears in this line": "le plus long qui apparaît dans cette ligne",
	"Line": "Ligne",
	"The Home Ward": "Le Quartier d'Accueil",
	"The Second Ward": "Le Second Quartier",
	"The Third Ward": "Le Troisième Quartier",
	"The Outer Reach": "Les confins extérieurs",
	"The Ash Champion": "Le champion des cendres",
	"It drinks from the grove and calls the grove its own.": "Il boit à la clairière et s'en dit le maître.",
	"The Iron Champion": "Le champion de fer",
	"It has been standing on the vein since before you arrived.": "Il se tient sur la veine depuis avant votre arrivée.",
	"The Outer Ward": "La garde extérieure",
	"The Ninth": "Le Neuvième",
	"The ninth disciple never left. It has been waiting at the top of the road.": "Le neuvième disciple n'est jamais parti. Il attend en haut de la route.",
	"how big the world is": "la taille du monde",
	"%s opens this ward — you are %s.": "%s ouvre cette garde — vous êtes %s.",
	"%s crossed. %s opens out in front of you.": "%s franchi. %s s'ouvre devant vous.",
	"Every ward is open and every champion is down. The road ends here — the world is ": "Toutes les gardes sont ouvertes et tous les champions sont tombés. La route se termine ici — le monde est ",
	"yours to walk, and nothing on it is holding you back.": "le vôtre à parcourir, et rien ne vous retient.",
	"how far to the next ward": "distance jusqu'à la prochaine garde",
	"what am I doing right now": "ce que je fais maintenant",
	"It holds %s, and it has been waiting a long time.": "Il contient %s, et il attend depuis longtemps.",
	"the last wall is behind you": "le dernier mur est derrière vous",
	"The road ends here": "La route se termine ici",
	"Every ward is open and every champion is down. The world is yours to walk.": "Toutes les gardes sont ouvertes et tous les champions sont tombés. Le monde est le vôtre à parcourir.",
	"all wards open": "toutes les gardes ouvertes",
	"%s It holds %s — the fastest ground you can cultivate on.": "%s Il contient %s — le terrain le plus rapide sur lequel vous pouvez cultiver.",
	"Break through to %s": "Percer jusqu'à %s",
	"%s needs %s. %s%s": "%s a besoin de %s. %s%s",
	"%s is awake — cultivate there, ": "%s est éveillé — cultivez là, ",
	"then walk the road out.": "puis marchez sur la route.",
	"%s is open": "%s est ouvert",
	"The wall has fallen. Walk out to %s.": "Le mur est tombé. Marchez vers %s.",
	"walk the road out": "marchez sur la route",
	"realm reached": "royaume atteint",
	"%d stage%s to %s": "%d stade%s à %s",
	"%s · %d/%d champions down": "%s · %d/%d champions abattus",
	"Someone is walking the road.": "Quelqu'un marche sur la route.",
	"Hold them. Hold them!": "Tenez-les. Tenez-les !",
	"You have come to the wrong ring.": "Vous êtes tombé dans le mauvais cercle.",
	"Body": "Corps",
	"Fight": "Combat",
	"Ranged": "Distance",
	"Rewards": "Récompenses",
	"Feedback": "Retour",
	"Reset": "Réinitialiser",
	"Model": "Modèle",
	"Walk": "Marcher",
	"Run": "Courir",
	"Attack": "Attaquer",
	"Death": "Mort",
	"Nameplate": "Plaque",
	"%s is down.": "%s est à terre.",
	"Raider down. +%d crystals.": "Pillards à terre. +%d cristaux.",
	"%s falls. +%d crystals%s": "%s tombe. +%d cristaux%s",
	"%s is awake, and there is no one left standing on it.": "%s est éveillé, et plus personne ne se tient debout dessus.",
	"nearest enemy": "ennemi le plus proche",
	"Enemy": "Ennemi",
	"the ranged attack does not\n work": "l'attaque à distance ne\n fonctionne pas",
	"Ring": "Anneau",
	"Rise": "Se lever",
	"running gets stuck after a while": "la course se bloque au bout d'un moment",
	"Roll": "Rouler",
	"swing the thigh out, then\n fold the knee under it": "balancier la cuisse dehors, puis\n plier le genou dessous",
	"Hips": "Hanches",
	"Torso": "Torse",
	"a pose was applied": "une posture a été appliquée",
	"the joints did not move": "les articulations n'ont pas bougé",
	"upgrade the lamp": "améliorer la lampe",
	"Lantern": "Lanterne",
	"Lamp": "Lampe",
	"Wick": "Mèche",
	"The lamp takes. %d metres of road.": "La lampe prend. %d mètres de route.",
	"The lamp goes out.": "La lampe s'éteint.",
	"Movement feel": "Sensation de mouvement",
	"Slopes and steps": "Pentes et marches",
	"Dash": "Ruée",
	"Collision feel": "Sensation de choc",
	"Fall damage": "Dégâts de chute",
	"Collapse": "Effondrement",
	"Stat income": "Revenu de statistiques",
	"Wayfaring": "Pélerinage",
	"no previous tap": "pas de frappe précédente",
	"Press C to sit and cultivate, B to break through.": "Appuyez sur C pour vous asseoir et cultiver, B pour percer.",
	"The cloud lets you down.": "Le nuage vous lâche.",
	"Not enough qi for that.": "Pas assez de qi pour cela.",
	"The breath runs out. The air lets you go.": "Le souffle s'épuise. L'air vous lâche.",
	"Cloud Step holds. Two taps let it go.": "Pas du Nuage tient. Deux frappes le lâchent.",
	"Landed from %.1f m.": "Atterri de %.1f m.",
	"You land hard. %d knocked off their feet.": "Vous atterrissez durement. %d mis sur le cul.",
	"Your body gives out.": "Votre corps cède.",
	"the camp": "le campement",
	"You wake in %s, whole.": "Vous vous réveillez à %s, entier.",
	"The ground lets go. You are at the fire again.": "Le sol lâche. Vous êtes de retour au feu.",
	"The blow breaks your attunement.": "Le coup brise votre harmonie.",
	"can I strike": "puis-je frapper",
	"can I move": "puis-je bouger",
	"the body's drill": "l'exercice du corps",
	"keep holding": "restez",
	"The pressure drops.": "La pression baisse.",
	"stay here": "restez ici",
	"is this spot free": "cette place est libre",
	"may a body be set down here": "peut-on poser un corps ici",
	"sustainable at a thousand": "durable à mille",
	"Qi Pressure needs %.0f QI held. You have %.0f.": "La Pression de Qi requiert %.0f QI. Vous avez %.0f.",
	"The dantian is empty — nothing to push out.": "Le dantian est vide — rien à expulser.",
	"Qi Pressure up — %.1f m, %.0f QI/s.": "Pression de Qi en hausse — %.1f m, %.0f QI/s.",
	"The pressure collapses — the dantian is dry.": "La pression s'effondre — le dantian est sec.",
	"Shell": "Carapace",
	"Pressure Light": "Lumière de Pression",
	"%s. ATTACK +%s.": "%s. ATTAQUE +%s.",
	"the post comes apart": "le poteau se défait",
	"The raider falls": "Le pillard tombe",
	"The watchman goes down": "Le guetteur tombe",
	"Somebody who lives here is on the ground": "Quelqu'un qui vit ici est à terre",
	"The post comes apart": "le poteau se défait",
	"how much is left": "combien reste-t-il",
	"%s\nGrows by: %s": "%s\nCroît de : %s",
	"Second\nWind": "Second\nVent",
	"%s — grows by: %s": "%s — croît de : %s",
	"Held: %s.": "Détenu : %s.",
	"Next: %s at %s — %s": "Prochain : %s à %s — %s",
	"next: ": "prochain : ",
	"No technique yet. Every stat turns into something at a multiple of its ": "Aucune technique pour l'instant. Chaque statistique se transforme en quelque chose à un multiple de sa ",
	"starting cap — the name appears at the end of that stat's row when it does.": "limite de départ — le nom apparaît à la fin de la ligne de cette statistique quand cela arrive.",
	"%d of %d held.": "%d sur %d détenu.",
	"    needs %s, have %s": "    besoin de %s, possession de %s",
	"1.3 HP": "1,3 PV",
	"Tap the key to start a set.": "Appuyez sur la touche pour commencer un ensemble.",
	"Costs %.1f%% of your health per rep.": "Coûte %.1f%% de votre santé par répétition.",
	"Costs %.1f%% of your qi per rep — and the deeper the pool, the faster the set.": "Coûte %.1f%% de votre qi par répétition — et plus le réservoir est profond, plus l'ensemble est rapide.",
	"Dim": "Faible",
	"Footer": "Pied de page",
	"Save": "Sauvegarder",
	"Close": "Fermer",
	"Row": "Rang",
	"SET ": "RÉGLER ",
	"Slider": "Curseur",
	"Header": "En-tête",
	"MAP": "CARTE",
	"Hide": "Cacher",
	"gold you · cyan wards · red raiders …": "or vous · gardes cyan · pillards rouges …",
	"Show": "Montrer",
	"Aura attuned: %s.": "Aura accordée : %s.",
	"INSIGHT %d%%": "APERÇU %d%%",
	"BODY  ·  HP %s  QI %s": "CORPS  ·  PV %s  QI %s",
	"%d reps": "%d répétitions",
	"tap %s to start": "touchez %s pour commencer",
	"Aura: %s · power %.0f%%": "Aura : %s · puissance %.0f%%",
	"ELDER SHUFEN": "ANCIEN SHUFEN",
	"Claim": "Réclamer",
	"Later": "Plus tard",
	"Holder": "Porte-objet",
	"Another\n time": "Une autre\n fois",
	"Leave": "Quitter",
	"Press 1-%d to answer · Esc to step away": "Appuyez sur 1-%d pour répondre · Échap pour vous éloigner",
	"Wares": "Marchandises",
	"Name": "Nom",
	"Detail": "Détail",
	"Cost": "Coût",
	"Buy": "Acheter",
	"THE PATH · %s": "LE SENTIER · %s",
	"%s — ready to hand in": "%s — prêt à être remis",
	"%s / %s   ·   %d crystals": "%s / %s   ·   %d cristaux",
	"   ·   %s — dormant, needs stage %d": "   ·   %s — dormant, besoin du stade %d",
	"E talk to the elder · 1 drill the body · X qi pressure · T recall · Tab settings · V stats": "E parler à l'ancien · 1 forger le corps · X pression du qi · T rappel · Tab réglages · V stats",
	"%s IN %s — %d crystals settles it": "%s DANS %s — %d cristaux règlent l'affaire",
	"Qi Pressure UP — %.1f m · %.0f QI/s · %d in the field": "Pression Qi AUGMENTÉE — %.1f m · %.0f QI/s · %d sur le terrain",
	"costs %.0f QI/s": "coûte %.0f QI/s",
	"Qi Pressure — X to raise · %.1f m now, %.1f m max · %s": "Pression Qi — X pour augmenter · %.1f m maintenant, %.1f m max · %s",
	"   ·   ATTUNING %.0f%% — hold T, a blow breaks it": "   ·   MISE AU POINT %.0f%% — maintenez T, un coup la brise",
	"Main": "Principal",
	"Player": "Joueur",
	"Landmarks": "Lieux",
	"%d of %d found": "%d sur %d trouvés",
	"%s wants %d": "%s veut %d",
	"%s is shut to you": "%s vous est fermé",
	"You": "Vous",
	"%d floors, deepest %d": "%d étages, le plus profond %d",
	"needs %s": "a besoin de %s",
	"%d of %d felled": "%d sur %d abattus",
	"needs stage %d": "a besoin du stade %d",
	"x%.1f qi": "x%.1f Qi",
	"where am I and what is out there": "où suis-je et qu'y a-t-il dehors",
	"somewhere you have not been": "quelque part où vous n'êtes pas allé",
	"Wayfinder": "Repère",
	"the marker stays on screen": "le repère reste à l'écran",
	"Blocker": "Bloqueur",
	"Pivot": "Pivoter",
	"walk to the zone": "aller dans la zone",
	" Camp": " Campement",
	"Bandit Hollow": "Gouffre des Brigands",
	"Ashfall Camp": "Campement des Cendres",
	"The Broken Wheel": "La Roue Brisée",
	"Thornwatch": "Garde-Épine",
	"Cinder Camp": "Camp Cendres",
	"Wolfrest": "Repos-du-Loup",
	"Greyridge Camp": "Camp Crête-Grise",
	"The Long Reach": "La Longue Portée",
	"Saltmarsh Watch": "Garde de Marais-Salants",
	"is the world supposed to have a champion fewer than the table lists": "le monde est censé avoir un champion de moins que ce qu'indique le tableau",
	"%s burns — %d raiders did not leave it.": "%s brûle — %d pillards ne sont pas repartis.",
	"%s is left standing. %d raiders will look the other way.": "%s reste debout. %d pillards détourneront le regard.",
	"what happens if I hit somebody": "que se passe-t-il si je frappe quelqu'un",
	"nothing, ever": "rien, jamais",
	"The Watch": "La Garde",
	"Halt. You are not walking past me.": "Halte. Vous ne passerez pas.",
	"We know your face. Walk quietly.": "Nous connaissons votre visage. Marchez discrètement.",
	"Enough. Put it down.": "Assez. Posez ça.",
	"Raiders at the wall!": "Pillards au mur !",
	"The watch has you. Sit down.": "La Garde vous a. Asseyez-vous.",
	"%s was struck": "%s a été frappé",
	"%s was killed in the open": "%s a été tué à découvert",
	"%s is down. Somebody else's fight, and the village knows it.": "%s est à terre. Le combat d'un autre, et le village le sait.",
	"what is over that hill": "qu'y a-t-il par-delà cette colline",
	"Seven stones on their ends, and a cold fire between them.": "Sept pierres sur leurs extrémités, et un feu froid entre elles.",
	"The Fallen Gate": "La Porte Déchue",
	"A doorway to a wall that is no longer there.": "Une porte vers un mur qui n'est plus là.",
	"The Grey Watch": "La Garde Grise",
	"A tower with the roof gone and the torch still lit.": "Une tour dont le toit a disparu et dont la torche brûle encore.",
	"The Quiet Shrine": "Le Sanctuaire Silencieux",
	"Somebody kept this swept. Somebody still does.": "Quelqu'un a maintenu ceci balayé. Quelqu'un le fait encore.",
	"The Traveller's Cairn": "Le Cairn du Voyageur",
	"Stones piled by every hand that passed, and a chest at its foot.": "Des pierres empilées par chaque main qui est passée, et un coffre à son pied.",
	"The Cold Forge": "La Forge Froide",
	"An anvil, a whetstone, and a stand with no weapon on it.": "Une enclume, une pierre à aiguiser, et un support sans arme dessus.",
	"The Broken Cart": "La Charrette Brisée",
	"Whatever it carried is scattered downhill from here.": "Ce qu'elle portait est dispersé en contrebas.",
	"The Hollow Oak": "Le Chêne Creux",
	"Old enough to have been a landmark before there were roads.": "Assez vieux pour avoir été un repère avant qu'il y ait des routes.",
	"The Sundered Stones": "Les Pierres Démembrées",
	"Split clean through, and not by weather.": "Fendues net, et pas par le temps.",
	"level enough": "assez de niveau",
	"ring %d: %d": "anneau %d : %d",
	"you find these by following a road": "vous trouvez ceux-ci en suivant une route",
	"come here": "venez ici",
	"Beacon": "Balise",
	"find two of the old places": "trouvez deux des anciens lieux",
	"%s — %s  +%d crystals.%s": "%s — %s  +%d cristaux.%s",
	"the nearest one": "celui qui est le plus proche",
	"the one whose coordinates you then fetch": "celui dont vous récupérez ensuite les coordonnées",
	"I will be able to use that one day": "je pourrai l'utiliser un jour",
	"this ground is dormant until stage five": "ce sol est dormant jusqu'au stade cinq",
	"Spirit Spring": "Source d'Esprit",
	"Whispering Grove": "Bosquet Murmurant",
	"Earth Vein": "Veine de Terre",
	"Storm Peak": "Pic de l'Orage",
	", relaxed": ", détendu",
	"a place": "un lieu",
	"Glow": "Lueur",
	"Spirit zone: %s — cultivating here runs at ×%.1f.": "Zone d'Esprit : %s — la culture ici se fait à ×%.1f.",
	"something is standing on it": "quelque chose s'y tient",
	"%s is asleep — %s is standing on it.": "%s dort — %s s'y tient.",
	"%s is dormant for you. It answers at stage %s.": "%s est dormant pour vous. Il répond au stade %s.",
	"Elder Shufen": "Ancienne Shufen",
	"Marker": "Marqueur",
	"you cannot get into the tower": "vous ne pouvez entrer dans la tour",
	"%s: \"Well done. Take these.\"": "%s : « Bien fait. Prenez ceci. »",
	"%s: \"You have done everything I know how to teach. The shelf is yours.\"": "%s : « Vous avez tout appris de ce que je sais enseigner. L'étagère est à vous. »",
	"where do I go when this goes badly": "où vais-je si cela tourne mal",
	"the home camp": "le campement",
	"The camp wards hold. Nothing here will follow you in.": "Les protections du camp tiennent. Rien ici ne vous suivra.",
	"You step beyond the camp wards.": "Vous franchissez les protections du camp.",
	"Boundary": "Frontière",
	"  MISSING %s": "  MANQUANT %s",
	"which model is this?": "quel modèle est-ce ?",
	"its slopes were all too gentle": "ses pentes étaient bien trop douces",
	"your density is 0.01": "votre densité est de 0.01",
	"Trunk": "Tronc",
	"Whispering Grove  62 m": "Bois des Murmures  62 m",
	"Text": "Texte",
	"Home camp": "Camp de base",
	"Roads": "Routes",
	"Mesh": "Maillage",
	"Shape": "Forme",
	"the tower's step": "la marche de la tour",
	"The tower's step. Nothing comes up to the door after you.": "La marche de la tour. Rien ne monte à la porte après vous.",
	"You step away from the tower's step.": "Vous vous éloignez de la marche de la tour.",
	"Plaza": "Esplanade",
	"Crown": "Couronne",
	"Doorway": "Entrée",
	"THE TOWER OF THE TENTH SEAT": "LA TOUR DU DIXIÈME SIÈGE",
	"Stage": "Étage",
	"Plate": "Plaque",
	"Ceiling": "Plafond",
	"Rim": "Bord",
	"Floor": "Plancher",
	"Floor %d · %s — %s": "Plancher %d · %s — %s",
	"Something has been left on this landing.": "Quelque chose a été laissé sur ce palier.",
	"There are more of them than usual here.": "Ils sont plus nombreux qu'à l'accoutumée.",
	"This floor is already yours. The way up is open.": "Cet étage vous appartient déjà. Le chemin vers le haut est ouvert.",
	"%s is standing at the top of this landing.": "%s se tient en haut de ce palier.",
	"More of them are coming down the stair.": "Ils descendent l'escalier par plus grand nombre.",
	"near the door": "près de la porte",
	"at the door": "à la porte",
	"talk to the elder": "parler à l'ancien",
	"speak with Sarn": "parler à Sarn",
	"at the foot of the tower": "au pied de la tour",
	"Square": "Place",
	"there is something there": "il y a quelque chose là",
	"%s Watch": "Garde %s",
	"You walk out through %s's gate.": "Vous sortez par la porte de %s.",
	"Lintel": "Linteau",
	"not yet": "pas encore",
	"the ward holds": "la garde tient",
	"the world ends here": "le monde finit ici",
	"%s thins and is gone. The way out is open.": "%s s'amincit et disparaît. Le chemin vers la sortie est ouvert.",
	"The ward holds you back. %s": "La garde vous retient. %s",
	"The ward holds you back.": "La garde vous retient.",
	"The ground ends here. Past this the world simply stops.": "Le sol s'arrête ici. Au-delà, le monde cesse simplement d'exister.",
	"You are put back inside %s. %s": "Vous êtes ramené à l'intérieur de %s. %s",
	"a locked ward is visible and an open one is not": "une salle verrouillée est visible et une autre ouverte ne l'est pas",
	"held back": "retenu",
	"never tested": "jamais éprouvé",
	"Sun": "Soleil",
	"Disantia. The path begins at the foot of the mountain.": "Disantia. Le chemin commence au pied de la montagne.",
	"You can be taught one thing today, and only one, because the two of them are opposite answers. A heavier hand, or a deeper breath. Which is it?": "Vous pouvez apprendre une chose aujourd'hui, et une seule, car les deux sont des réponses opposées. Une main plus lourde, ou une respiration plus profonde. Laquelle est-ce ?",
	"You have been out there, so you know. The raiders burn the road for whoever walks it — and they were somebody's sons before they were anybody's problem. Burn their camp with them in it, or take the road past it and let them live?": "Vous avez été là-bas, vous savez donc. Les pillards brûlent la route pour quiconque la parcourt — et ils étaient les fils de quelqu'un avant d'être le problème de qui que ce soit. Brûler leur camp avec eux dedans, ou prendre la route au-delà et les laisser vivre ?",
	"Found this on the road. The elder's own ledger, with his prices in it. I could walk it back to him, or we could both just... not notice.": "Trouvé ceci sur la route. Le registre de l'ancien lui-même, avec ses prix. Je pourrais le lui rapporter, ou nous pourrions simplement... ne pas le remarquer.",
	"The anvil at Stonewatch can take it further.": "L'enclume de la Garde de Pierre peut aller plus loin.",
	"Material and crystals, and it comes out better than it went on. It will never be worth more than the arm swinging it.": "Matière et cristaux, et ça ressort mieux qu'à l'entrée. Ça ne vaudra jamais plus que le bras qui le manie.",
	"A name is a contract. Take one and the body stands at that camp until it is down, then bring the proof back here.": "Un nom est un contrat. Prenez-en un et le corps se tient à ce camp jusqu'à ce qu'il soit abattu, puis rapportez la preuve ici.",
	"Nothing in the valley has been further.": "Rien dans la vallée n'est allé plus loin.",
	# ------------------------------------------------- translated from the game's own
	# strings, by `tools/translate_fr.py`. Same rules as everything above: the English
	# is the key, and the placeholders are checked before a row is written.

	"%s cap +%s": "%s max +%s",
	"1.8% of your health per rep": "1.8% de votre santé par répétition",
	# ------------------------------------------------- translated from the game's own
	# strings, by `tools/translate_fr.py`. Same rules as everything above: the English
	# is the key, and the placeholders are checked before a row is written.

	"A deep breath, bottled. Restores 45% of the pool.": "Une profonde inspiration, mise en bouteille. Restaure 45% de la réserve.",
	"+35% on every blow for 45 seconds.": "+35% à chaque coup pendant 45 secondes.",
	"A blow carries: a second body within 2.2 m takes 40% of it.": "Un coup porte : un second corps à moins de 2,2 m en subit 40%.",
}
