extends RefCounted
## The spoken lines, and which file holds each one.
##
## Generated by `tools/make_voice.py` from the prose in the game's own tables — **do not edit by
## hand**. The English sentence is the key, the same way it is everywhere else in the interface
## (see `loc.gd`): a line with no row here is simply a line nobody has recorded yet, and the game
## says it in silence rather than breaking.
##
## A language is a *set of files*, not a translation of a file. A voice reading French words with
## an English mouth is worse than no voice at all, so `fr` is its own recording and a line that
## has no French take is played in English.
##
## Three tables, and the reason for each is in the tool that writes them:
##
##   * `TABLE` — whole lines, the prose somebody says to your face.
##   * `PHRASES` — the fixed half of a sentence with a number in it, which is the only way a line
##     like `Took 12.4 damage.` can ever be heard.
##   * `SHOUTS` — the cries, which are said rather than printed and so live here alone.


## `{ English line: { "en": "res://...", "fr": "res://..." } }`
const TABLE: Dictionary = {
	", taken \u2014 it is waiting for you.": {"en": "res://assets/voice/en/c0d04e7f7a94.mp3", "fr": "res://assets/voice/fr/c0d04e7f7a94.mp3"},
	"A door in the wall that opens onto more wall.": {"en": "res://assets/voice/en/35eff84643cd.mp3", "fr": "res://assets/voice/fr/35eff84643cd.mp3"},
	"A landing with no window, and a draught coming from somewhere.": {"en": "res://assets/voice/en/aed7bf4d7c80.mp3", "fr": "res://assets/voice/fr/aed7bf4d7c80.mp3"},
	"A name is a contract. Take one and the body stands at that camp until it is down, then bring the proof back here.": {"en": "res://assets/voice/en/e8bf6ff887f9.mp3", "fr": "res://assets/voice/fr/e8bf6ff887f9.mp3"},
	"A step finished is a step paid.": {"en": "res://assets/voice/en/251bedadcbc4.mp3", "fr": "res://assets/voice/fr/251bedadcbc4.mp3"},
	"Bring the material and the crystals and it comes out better.": {"en": "res://assets/voice/en/285aa660d4b5.mp3", "fr": "res://assets/voice/fr/285aa660d4b5.mp3"},
	"Buy something to wear first \u2014 the traders at the other villages keep the pieces.": {"en": "res://assets/voice/en/d69a2e39184e.mp3", "fr": "res://assets/voice/fr/d69a2e39184e.mp3"},
	"Carry Mei's letter to Warden Bai in Stonewatch, past the ward.": {"en": "res://assets/voice/en/491baf225778.mp3", "fr": "res://assets/voice/fr/491baf225778.mp3"},
	"Come back from the tenth floor of the tower alive.": {"en": "res://assets/voice/en/b5b8a205492b.mp3", "fr": "res://assets/voice/fr/b5b8a205492b.mp3"},
	"Du has finished a commission for Towerfall. Carry it there.": {"en": "res://assets/voice/en/4e5f673b76be.mp3", "fr": "res://assets/voice/fr/4e5f673b76be.mp3"},
	"Du will work for four Hide Scrap. The near raiders carry them.": {"en": "res://assets/voice/en/7ba5c5cab22b.mp3", "fr": "res://assets/voice/fr/7ba5c5cab22b.mp3"},
	"Ever downward is free, and a cleared floor stays clear.": {"en": "res://assets/voice/en/f6498979fc8c.mp3", "fr": "res://assets/voice/fr/f6498979fc8c.mp3"},
	"Every raider carries a shard or two.": {"en": "res://assets/voice/en/3656a3161bcd.mp3", "fr": "res://assets/voice/fr/3656a3161bcd.mp3"},
	"Follow a road out of camp. Anything the map wants you to find is tall and lit.": {"en": "res://assets/voice/en/74b056ecf3be.mp3", "fr": "res://assets/voice/fr/74b056ecf3be.mp3"},
	"Found this on the road. The elder's own ledger, with his prices in it. I could walk it back to him, or we could both just... not notice.": {"en": "res://assets/voice/en/a39382a73ce2.mp3", "fr": "res://assets/voice/fr/a39382a73ce2.mp3"},
	"Have anything forged to *good* \u2014 one upgrade at the anvil.": {"en": "res://assets/voice/en/32852089da36.mp3", "fr": "res://assets/voice/fr/32852089da36.mp3"},
	"He carries other people's accounts.": {"en": "res://assets/voice/en/6de92353d831.mp3", "fr": "res://assets/voice/fr/6de92353d831.mp3"},
	"He is the one who asks what your hands are for.": {"en": "res://assets/voice/en/36a5597c0ce7.mp3", "fr": "res://assets/voice/fr/36a5597c0ce7.mp3"},
	"Hollowmere \u2014 a well, four roofs, and a palisade somebody mended twice.": {"en": "res://assets/voice/en/d0c715b7363c.mp3", "fr": "res://assets/voice/fr/d0c715b7363c.mp3"},
	"I have heard what you did. I would rather not be the one who repeats it.": {"en": "res://assets/voice/en/b450c6e96270.mp3", "fr": "res://assets/voice/fr/b450c6e96270.mp3"},
	"Iron on every wall, and it has been counting the pieces.": {"en": "res://assets/voice/en/1df3b1ed08de.mp3", "fr": "res://assets/voice/fr/1df3b1ed08de.mp3"},
	"It has not needed eyes for a long time.": {"en": "res://assets/voice/en/f0e73267ae70.mp3", "fr": "res://assets/voice/fr/f0e73267ae70.mp3"},
	"It has swept this landing for a hundred years and it will not be told to stop.": {"en": "res://assets/voice/en/f1fb765ee334.mp3", "fr": "res://assets/voice/fr/f1fb765ee334.mp3"},
	"It is standing. Whatever you were about to pay for, it was not that.": {"en": "res://assets/voice/en/1a050bee7f6f.mp3", "fr": "res://assets/voice/fr/1a050bee7f6f.mp3"},
	"It wears what the first ward left of its own champion.": {"en": "res://assets/voice/en/69196c7e9c9c.mp3", "fr": "res://assets/voice/fr/69196c7e9c9c.mp3"},
	"Jump again in mid-air once this is yours \u2014 and mind the landing.": {"en": "res://assets/voice/en/c316cba46d51.mp3", "fr": "res://assets/voice/fr/c316cba46d51.mp3"},
	"Material and crystals, and it comes out better than it went on. It will never be worth more than the arm swinging it.": {"en": "res://assets/voice/en/6bb70965e36b.mp3", "fr": "res://assets/voice/fr/6bb70965e36b.mp3"},
	"Mind the sparks. Everything here is either being made or being repaired.": {"en": "res://assets/voice/en/e3cf9d4366cb.mp3", "fr": "res://assets/voice/fr/e3cf9d4366cb.mp3"},
	"Mm. Walk with me a little. I have the legs for it and nothing else.": {"en": "res://assets/voice/en/3e75ff28d006.mp3", "fr": "res://assets/voice/fr/3e75ff28d006.mp3"},
	"Names, cut into the wall in a hand that gets worse as it goes down.": {"en": "res://assets/voice/en/0df4f480d142.mp3", "fr": "res://assets/voice/fr/0df4f480d142.mp3"},
	"Ninety-nine floors you have not seen, and the ones you have are empty.": {"en": "res://assets/voice/en/925bbd53254d.mp3", "fr": "res://assets/voice/fr/925bbd53254d.mp3"},
	"Nobody has anything for sale until it is standing again.": {"en": "res://assets/voice/en/14e4142c575a.mp3", "fr": "res://assets/voice/fr/14e4142c575a.mp3"},
	"Not enough crystals for another.": {"en": "res://assets/voice/en/63658382fed6.mp3", "fr": "res://assets/voice/fr/63658382fed6.mp3"},
	"Not enough crystals for that one.": {"en": "res://assets/voice/en/cb6e15c898f9.mp3", "fr": "res://assets/voice/fr/cb6e15c898f9.mp3"},
	"Not enough of what it is made of, or not enough crystals.": {"en": "res://assets/voice/en/abfa3be109d4.mp3", "fr": "res://assets/voice/fr/abfa3be109d4.mp3"},
	"Not yet \u2014 there is more to do before that.": {"en": "res://assets/voice/en/22557ff12e74.mp3", "fr": "res://assets/voice/fr/22557ff12e74.mp3"},
	"Nothing in the valley has been further.": {"en": "res://assets/voice/en/e540c3859273.mp3", "fr": "res://assets/voice/fr/e540c3859273.mp3"},
	"Nothing in the valley has ever reached the hundredth floor.": {"en": "res://assets/voice/en/eec8d8742bfb.mp3", "fr": "res://assets/voice/fr/eec8d8742bfb.mp3"},
	"Nothing of yours to settle there.": {"en": "res://assets/voice/en/a1097caacf4d.mp3", "fr": "res://assets/voice/fr/a1097caacf4d.mp3"},
	"Old blood on the floor, and a broom left standing in it.": {"en": "res://assets/voice/en/95fe21ceca62.mp3", "fr": "res://assets/voice/fr/95fe21ceca62.mp3"},
	"Quiet, in the way a room is quiet after an argument.": {"en": "res://assets/voice/en/a4dd3c6377d1.mp3", "fr": "res://assets/voice/fr/a4dd3c6377d1.mp3"},
	"Raiders keep to their own ground. Strike them, then step back out of reach.": {"en": "res://assets/voice/en/0ca285dddaa8.mp3", "fr": "res://assets/voice/fr/0ca285dddaa8.mp3"},
	"Scholar Yun has been reading the same three pages for nine years.": {"en": "res://assets/voice/en/b7fcc72d9a67.mp3", "fr": "res://assets/voice/fr/b7fcc72d9a67.mp3"},
	"She has watched every camp smoke from up here.": {"en": "res://assets/voice/en/3c753e48bf9c.mp3", "fr": "res://assets/voice/fr/3c753e48bf9c.mp3"},
	"Shift to run. The metres count only while you are actually moving.": {"en": "res://assets/voice/en/a2cdaf17746e.mp3", "fr": "res://assets/voice/fr/a2cdaf17746e.mp3"},
	"Somebody in another village is waiting for it.": {"en": "res://assets/voice/en/05573f3b7ee1.mp3", "fr": "res://assets/voice/fr/05573f3b7ee1.mp3"},
	"Somebody said your name in the square and nobody asked who.": {"en": "res://assets/voice/en/6f0b64f66adf.mp3", "fr": "res://assets/voice/fr/6f0b64f66adf.mp3"},
	"Somebody scratched a count into the wall here. The last number is not finished.": {"en": "res://assets/voice/en/cfd88865359d.mp3", "fr": "res://assets/voice/fr/cfd88865359d.mp3"},
	"Something has been stacked here, neatly, for a long time.": {"en": "res://assets/voice/en/a7c3dad00bd8.mp3", "fr": "res://assets/voice/fr/a7c3dad00bd8.mp3"},
	"Stand still and let Elder Mei tell you what you have walked into.": {"en": "res://assets/voice/en/dab4a5ec1510.mp3", "fr": "res://assets/voice/fr/dab4a5ec1510.mp3"},
	"Stand there a moment. Feet apart. Yes \u2014 you have been running, not standing.": {"en": "res://assets/voice/en/2138b552eb32.mp3", "fr": "res://assets/voice/fr/2138b552eb32.mp3"},
	"Stonewatch \u2014 hammer, smoke, and a palisade of new-cut timber.": {"en": "res://assets/voice/en/00c41436a412.mp3", "fr": "res://assets/voice/fr/00c41436a412.mp3"},
	"That name cannot be taken from here.": {"en": "res://assets/voice/en/89294c0af1b1.mp3", "fr": "res://assets/voice/fr/89294c0af1b1.mp3"},
	"The Ninth left something behind on the way down. It has been waiting.": {"en": "res://assets/voice/en/34fd4b6ecf1c.mp3", "fr": "res://assets/voice/fr/34fd4b6ecf1c.mp3"},
	"The anvil at Stonewatch can take it further.": {"en": "res://assets/voice/en/e2229d3d30b8.mp3", "fr": "res://assets/voice/fr/e2229d3d30b8.mp3"},
	"The clerk will have new names by tomorrow.": {"en": "res://assets/voice/en/7eee3940b9c5.mp3", "fr": "res://assets/voice/fr/7eee3940b9c5.mp3"},
	"The door does not move. It is waiting for a body with more behind it than it has in front of it.": {"en": "res://assets/voice/en/095b6eb83a32.mp3", "fr": "res://assets/voice/fr/095b6eb83a32.mp3"},
	"The fire is for whoever comes back. It does not ask what you did out there.": {"en": "res://assets/voice/en/81df5efdd259.mp3", "fr": "res://assets/voice/fr/81df5efdd259.mp3"},
	"The floors it keeps are silent. It would like to keep yours.": {"en": "res://assets/voice/en/043245b2e713.mp3", "fr": "res://assets/voice/fr/043245b2e713.mp3"},
	"The gate goes back up, and the first stall opens before the last post is in.": {"en": "res://assets/voice/en/d3acb25c8ffb.mp3", "fr": "res://assets/voice/fr/d3acb25c8ffb.mp3"},
	"The last champion is standing on the last spirit zone. Take it from it.": {"en": "res://assets/voice/en/2e27fb36a4cb.mp3", "fr": "res://assets/voice/fr/2e27fb36a4cb.mp3"},
	"The light comes from the stone itself on this floor.": {"en": "res://assets/voice/en/e043f619a5d7.mp3", "fr": "res://assets/voice/fr/e043f619a5d7.mp3"},
	"The roads are levelled for exactly this.": {"en": "res://assets/voice/en/ec9975af3e7a.mp3", "fr": "res://assets/voice/fr/ec9975af3e7a.mp3"},
	"The stair turns, and the air changes.": {"en": "res://assets/voice/en/c5d2dcd9f2d5.mp3", "fr": "res://assets/voice/fr/c5d2dcd9f2d5.mp3"},
	"The steps are worn deepest in the middle, from feet that were not hurrying.": {"en": "res://assets/voice/en/630ac0631936.mp3", "fr": "res://assets/voice/fr/630ac0631936.mp3"},
	"The wards were built around this floor, and this floor has been awake the whole time.": {"en": "res://assets/voice/en/2ccc101e7904.mp3", "fr": "res://assets/voice/fr/2ccc101e7904.mp3"},
	"The windows up here look out on nothing at all.": {"en": "res://assets/voice/en/9c21fd1cf5fb.mp3", "fr": "res://assets/voice/fr/9c21fd1cf5fb.mp3"},
	"Then there is nothing to ask.": {"en": "res://assets/voice/en/12cf30b0b2df.mp3", "fr": "res://assets/voice/fr/12cf30b0b2df.mp3"},
	"There is a place up the road nobody tends and everybody knows. Find it.": {"en": "res://assets/voice/en/7b689f56cf83.mp3", "fr": "res://assets/voice/fr/7b689f56cf83.mp3"},
	"There is nothing above this one that will let you in.": {"en": "res://assets/voice/en/5fe8873890e7.mp3", "fr": "res://assets/voice/fr/5fe8873890e7.mp3"},
	"There is nothing below you but the ground.": {"en": "res://assets/voice/en/763d108d8434.mp3", "fr": "res://assets/voice/fr/763d108d8434.mp3"},
	"There were twelve of you once, it says. There is one of you now.": {"en": "res://assets/voice/en/d28ab22fff0f.mp3", "fr": "res://assets/voice/fr/d28ab22fff0f.mp3"},
	"They have stopped asking what you want and started asking what you need.": {"en": "res://assets/voice/en/8d6f03c1a048.mp3", "fr": "res://assets/voice/fr/8d6f03c1a048.mp3"},
	"They look at you the way people look at weather coming in.": {"en": "res://assets/voice/en/169f77a6d620.mp3", "fr": "res://assets/voice/fr/169f77a6d620.mp3"},
	"They say your name now, further down the road. They say it carefully.": {"en": "res://assets/voice/en/7c76dbf4bcc4.mp3", "fr": "res://assets/voice/fr/7c76dbf4bcc4.mp3"},
	"They will not start it without the price in hand.": {"en": "res://assets/voice/en/20a4a4b00fb1.mp3", "fr": "res://assets/voice/fr/20a4a4b00fb1.mp3"},
	"This is the village's whole story, and it is three steps long.": {"en": "res://assets/voice/en/e43b56685761.mp3", "fr": "res://assets/voice/fr/e43b56685761.mp3"},
	"Towerfall \u2014 the spire's shadow lies over the whole square, and nobody looks up.": {"en": "res://assets/voice/en/032fddcda9bc.mp3", "fr": "res://assets/voice/fr/032fddcda9bc.mp3"},
	"You are new here. It is in the shoulders.": {"en": "res://assets/voice/en/29dfb97e132b.mp3", "fr": "res://assets/voice/fr/29dfb97e132b.mp3"},
	"You are somebody's rumour now, you know.": {"en": "res://assets/voice/en/3e1d0b129893.mp3", "fr": "res://assets/voice/fr/3e1d0b129893.mp3"},
	"You came down the road, so you are somebody's news. Sit. Nothing here is in a hurry.": {"en": "res://assets/voice/en/8ff8ff3d1d5d.mp3", "fr": "res://assets/voice/fr/8ff8ff3d1d5d.mp3"},
	"You can be taught one thing today, and only one, because the two of them are opposite answers. A heavier hand, or a deeper breath. Which is it?": {"en": "res://assets/voice/en/73dfa9a5e1db.mp3", "fr": "res://assets/voice/fr/73dfa9a5e1db.mp3"},
	"You cannot cover the fee, and she does not work on credit.": {"en": "res://assets/voice/en/8bd63fd872a8.mp3", "fr": "res://assets/voice/fr/8bd63fd872a8.mp3"},
	"You cannot cover the price, and nobody in the valley works on credit.": {"en": "res://assets/voice/en/57280fb47006.mp3", "fr": "res://assets/voice/fr/57280fb47006.mp3"},
	"You have been out there, so you know. The raiders burn the road for whoever walks it \u2014 and they were somebody's sons before they were anybody's problem. Burn their camp with them in it, or take the road past it and let them live?": {"en": "res://assets/voice/en/a62a0a69feca.mp3", "fr": "res://assets/voice/fr/a62a0a69feca.mp3"},
	"You have climbed further than it expected. It intends to fix that.": {"en": "res://assets/voice/en/ffe06ca2a188.mp3", "fr": "res://assets/voice/fr/ffe06ca2a188.mp3"},
	"You have grown since last I looked. It shows in how you stand.": {"en": "res://assets/voice/en/6e9ef3ce7383.mp3", "fr": "res://assets/voice/fr/6e9ef3ce7383.mp3"},
	"You have seen it. Everybody who arrives has seen it. The question is why you came anyway.": {"en": "res://assets/voice/en/551b8cb97483.mp3", "fr": "res://assets/voice/fr/551b8cb97483.mp3"},
	"You keep the depth you have taken. You lose nothing but the climb.": {"en": "res://assets/voice/en/37a02c713698.mp3", "fr": "res://assets/voice/fr/37a02c713698.mp3"},
	"left to say, but it is what I can do.": {"en": "res://assets/voice/en/b83c16733486.mp3", "fr": "res://assets/voice/fr/b83c16733486.mp3"},
	"road out there is not getting shorter.": {"en": "res://assets/voice/en/09a9774a4cbe.mp3", "fr": "res://assets/voice/fr/09a9774a4cbe.mp3"},
	"walking out of that gate either way.": {"en": "res://assets/voice/en/0a37c20d8acc.mp3", "fr": "res://assets/voice/fr/0a37c20d8acc.mp3"},
}

## The fixed halves of the game's dynamic sentences, longest match wins.
const PHRASES: Dictionary = {
	"A wound closes.": {"en": "res://assets/voice/en/aeb507794a05.mp3", "fr": "res://assets/voice/fr/37666f802b2b.mp3"},
	"Body remembers.": {"en": "res://assets/voice/en/a1146a3709a6.mp3", "fr": "res://assets/voice/fr/b6d5a224e119.mp3"},
	"Des coureurs sur la route au cr\u00e9puscule.": {"en": "res://assets/voice/en/34d346030a06.mp3"},
	"L'amende est pay\u00e9e.": {"en": "res://assets/voice/en/acd58fe12913.mp3"},
	"La garde vous retient.": {"en": "res://assets/voice/en/fde77c2f2505.mp3"},
	"La lampe prend.": {"en": "res://assets/voice/en/2051777a2373.mp3"},
	"Le corps se souvient.": {"en": "res://assets/voice/en/b6d5a224e119.mp3"},
	"Les volets sont lev\u00e9s.": {"en": "res://assets/voice/en/0f085d6f88f1.mp3"},
	"Perc\u00e9e !": {"en": "res://assets/voice/en/66d35d962cc0.mp3"},
	"Runners on the road at dusk.": {"en": "res://assets/voice/en/6fcc36ecb3b9.mp3", "fr": "res://assets/voice/fr/34d346030a06.mp3"},
	"The fine is paid.": {"en": "res://assets/voice/en/15136ba3e90e.mp3", "fr": "res://assets/voice/fr/acd58fe12913.mp3"},
	"The lamp takes.": {"en": "res://assets/voice/en/746f2b98877c.mp3", "fr": "res://assets/voice/fr/2051777a2373.mp3"},
	"The shutters are up.": {"en": "res://assets/voice/en/43e3f229a958.mp3", "fr": "res://assets/voice/fr/0f085d6f88f1.mp3"},
	"The ward holds you back.": {"en": "res://assets/voice/en/daf121e2bf44.mp3", "fr": "res://assets/voice/fr/fde77c2f2505.mp3"},
	"Une blessure se referme.": {"en": "res://assets/voice/en/37666f802b2b.mp3"},
	"Vous atterrissez durement.": {"en": "res://assets/voice/en/81d9a3f663df.mp3"},
	"Vous avez d\u00e9j\u00e0 choisi.": {"en": "res://assets/voice/en/ea22ee2d077c.mp3"},
	"You already chose.": {"en": "res://assets/voice/en/ed98ee05d531.mp3", "fr": "res://assets/voice/fr/ea22ee2d077c.mp3"},
	"You land hard.": {"en": "res://assets/voice/en/3eb609d26246.mp3", "fr": "res://assets/voice/fr/81d9a3f663df.mp3"},
}

## What the watch and the raiders say out loud.
const SHOUTS: Dictionary = {
	"Enough. Put it down.": {"en": "res://assets/voice/en/354911b56fb3.mp3", "fr": "res://assets/voice/fr/354911b56fb3.mp3"},
	"Halt. You are not walking past me.": {"en": "res://assets/voice/en/869820754398.mp3", "fr": "res://assets/voice/fr/869820754398.mp3"},
	"Hold them. Hold them!": {"en": "res://assets/voice/en/492b874e0c82.mp3", "fr": "res://assets/voice/fr/492b874e0c82.mp3"},
	"Raiders at the wall!": {"en": "res://assets/voice/en/cd4e3231d35f.mp3", "fr": "res://assets/voice/fr/cd4e3231d35f.mp3"},
	"Someone is walking the road.": {"en": "res://assets/voice/en/5572d4c402d2.mp3", "fr": "res://assets/voice/fr/5572d4c402d2.mp3"},
	"The watch has you. Sit down.": {"en": "res://assets/voice/en/ea079b4bf42e.mp3", "fr": "res://assets/voice/fr/ea079b4bf42e.mp3"},
	"We know your face. Walk quietly.": {"en": "res://assets/voice/en/30900d4e1d88.mp3", "fr": "res://assets/voice/fr/30900d4e1d88.mp3"},
	"You have come to the wrong ring.": {"en": "res://assets/voice/en/b2b145ef93f8.mp3", "fr": "res://assets/voice/fr/b2b145ef93f8.mp3"},
}
